### ISSUE TITLE
Overflow on % Morph

### ISSUE THREAD

**Issue by crazysquirrel622** [Tachyonite/Pawnmorpher#76] opened 2020-03-01 08:31 UTC
Attempting to inject a pawn with a mutaserum seems to cause no mutations to the pawn (pawn still transforms into the animal if not given stabilizer). Giving that pawn a chaobulb seedpod causes them to gain a mutated part, but under mutations tab it shows that pawn is -2147483648% of creature that part if from. Issue seems to only occur after playing a save for an amount of time (if I start a new save and give a pawn a mutaserum, they mutate like normal). Issue with pawn not mutating from the serum, and having the -2147483648% of creature likely linked?

Have some time pass in a colony, give a pawn a chaobulb seedpod or inject them with a mutaserum. Observe results

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/f62ad51db22de76bebd380c200feba11

**Expected behavior**
Besides the mutaserum slowly mutating a pawn, a pawns % of being a morph shouldn't overflow like it does in my case.

**Screenshots**
https://imgur.com/a/IAz4r3A

**Additional context**
No error log pop up when the issue occurs.
Should also mention this started to happen in 1.0 as well when the 1.7 update for pawnmorpher released

**Comment by FxWolfxe** [comment] 2020-03-01 13:37
Duplicate of #74 closing this issue and re opening that one

**Closed by FxWolfxe** 2020-03-01 13:37 UTC
Labels: bug
